# Generated by Django 2.2 on 2019-05-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField()),
                ('vehicle_number', models.BigIntegerField()),
                ('image', models.FileField(upload_to='static/')),
                ('username', models.CharField(max_length=100)),
            ],
        ),
    ]
