# Generated by Django 2.2 on 2019-05-12 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='validated',
            field=models.BooleanField(default=False, help_text='Only if it is verified'),
        ),
    ]
