# Generated by Django 2.2 on 2019-05-15 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190515_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=0.0, max_length=20)),
                ('lng', models.FloatField(default=0.0, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='appuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='app_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cabuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appuser',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
        ),
        migrations.AddField(
            model_name='cabuser',
            name='location',
            field=models.OneToOneField(blank=True, default=0.0, on_delete=django.db.models.deletion.CASCADE, to='accounts.Location'),
            preserve_default=False,
        ),
    ]
