# Generated by Django 2.2 on 2019-05-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190515_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabuser',
            name='license_no',
            field=models.CharField(default='000000000', max_length=30),
        ),
        migrations.AddField(
            model_name='cabuser',
            name='vehicle_no',
            field=models.CharField(default='XYZ 0000', max_length=30),
        ),
    ]
