# Generated by Django 2.2 on 2019-05-16 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190516_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabuser',
            name='location',
        ),
        migrations.RemoveField(
            model_name='cabuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_driver',
        ),
        migrations.DeleteModel(
            name='AppUser',
        ),
        migrations.DeleteModel(
            name='CabUser',
        ),
    ]
