# Generated by Django 2.2 on 2019-05-21 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190521_0816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='phone number must be entered in folloeing format *********', regex='^\\+?1?\\d{9,14}$')]),
        ),
    ]
