### validate user

POST https://havelorryapp.herokuapp.com/api/validate/
Content-Type: application/json

{
    "phone":"9893707504"
}


### Verify
POST https://havelorryapp.herokuapp.com/api/verify_otp/
Content-Type: application/json

{
    "phone":"9893707504",
    "otp":"574941"
}

### Register

POST https://havelorryapp.herokuapp.com/api/register/
Content-Type: application/json

{
    "phone":"9893707504"
}

### login

POST https://havelorryapp.herokuapp.com/api/login/
Content-Type: application/json

{
    "phone":"9893707504"
}

### local login
POST https://havelorryapp.herokuapp.com/api/login/
Content-Type: application/json

{
    "phone":"9893707504"
}

### GET Profile
GET  https://havelorryapp.herokuapp.com/api/profile/ HTTP/1.1
Content-Type: application/json
Authorization: Token 44514d5663b2c297f62d6a2dfe5e7275e8bb178c44cb9b727cb56530d6f47927

