### validate user

POST http://127.0.0.1:8000/api/validate/
Content-Type: application/json

{
    "phone":"9893707504"
}


### Verify
POST http://127.0.0.1:8000/api/verify_otp/
Content-Type: application/json

{
    "phone":"9893707504",
    "otp":"574941"
}

### Register

POST http://127.0.0.1:8000/api/register/
Content-Type: application/json

{
    "phone":"9893707504"
}

### login

POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "phone":"9893707504"
}

### local login
POST http://127.0.0.1:8000/api/login/
Content-Type: application/json

{
    "phone":"9893707504"
}

### GET Profile
GET  http://127.0.0.1:8000/api/profile/ HTTP/1.1
Content-Type: application/json
Authorization: Token 44514d5663b2c297f62d6a2dfe5e7275e8bb178c44cb9b727cb56530d6f47927

### driver login
POST http://localhost:8000/driver/login/
Content-Type: application/json

{
	"username":"9897571118","password":"bhole"
}